velodyne_driver_node:
    ros__parameters:
            #33device_ip: 192.168.1.201
        gps_time: false
        time_offset: 0.0
        enabled: false
        read_once: false
        read_fast: false
        repeat_delay: 0.0
        frame_id: velodyne
        model: 32C
        rpm: 600.0
        port: 2368
        pcap: lidar1.pcap
